clinify/config/routes.rb
Clinify::Application.routes.draw do

  resources :records
  resources :users do
     get "search"
     get "searchname"
  end
  resources :sessions, only: [:new, :create, :destroy]

  root  :to => 'clinify_static_pages#home' , via: 'get'

  match '/help' , to: 'clinify_static_pages#help', via: 'get'

  match '/about' , to: 'clinify_static_pages#about', via: 'get'

  match '/login' , to: 'sessions#new', via: 'get'
  match '/logout' , to: 'sessions#destroy', via: 'delete'

end

clinify/app/models/record.rb
class Record < ActiveRecord::Base
	belongs_to :user
	validates :symptoms, :beats, :history, presence: true
	validates :obs, length: {maximum: 100}
end

clinify/app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true
	validates :login , length: {maximum: 8}, length: {minimum: 5}
	validates_uniqueness_of :login
	validates :senha, length: {maximum: 10}, length: {minimum: 6}
end

clinify/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

clinify/app/controllers/clinify_static_pages_controller.rb
class ClinifyStaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def login
  end
  
end

clinify/app/controllers/records_controller.rb
class RecordsController < ApplicationController
  # GET /records
  # GET /records.json
  def index
    @records = Record.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @records }
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Record.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/new
  # GET /records/new.json
  def new
    @record = Record.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @record }
    end
  end

  # GET /records/1/edit
  def edit
    @record = Record.find(params[:id])
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(params[:record])

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Cadastro realizado com sucesso.' }
        format.json { render json: @record, status: :created, location: @record }
      else
        format.html { render action: "new" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])

    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to @record, notice: 'Cadastro atualizado com sucesso.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record = Record.find(params[:id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :ok }
    end
  end
end

clinify/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
    	if user && user.authenticate(params[:session][:password])
       		sign_in user
      		redirect_to user
  		else
     	 	flash.now[:error] = 'Invalid email/password combination'
      		render 'new'
   		end
	end

	def destroy
		
	end
end

clinify/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

 # GET /user/search
  def search

  end
  
  def searchname
    @users = User.all
  end
  
  
  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuario cadastro com sucesso.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Usuario atualizado com sucesso.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

clinify/app/helpers/application_helper.rb
module ApplicationHelper

	#returns the full title on a per-page basis

	def full_title(page_title)
		base_title = "Kefisio"
		if page_title.empty?
			base_title
		else 
			"#{base_title} | #{page_title}"
		end
	end
end

clinify/app/helpers/clinify_static_pages_helper.rb
module ClinifyStaticPagesHelper
end

clinify/app/helpers/records_helper.rb
module RecordsHelper
end

clinify/app/helpers/sessions_helper.rb
module SessionsHelper
end

clinify/app/helpers/users_helper.rb
module UsersHelper
end

clinify/app/views/clinify_static_pages/about.html.erb
<%provide(:title, 'About us') %>
<h1> Sobre nós </h1>
<p>
	Somos uma clínica de fisioterapia com foco em estética, fisioterapia motora e Pilates.
	Acesse nossa <a href="https://www.facebook.com/kefisio.kefisio/about"> página no Facebook. </a>
	
<p> Nosso endereço é 
	          	Rua Pedro Pereira de Almeida, 11
	          	58417540 Sítio Campina Grande, Brazil
	          	Bairro Presidente Médici
</p>
	
<p> Como chegar? <a href="https://www.google.com.br/maps/dir/R.+Pedro+Pereira+de+Almeida,+11+-+%E3%83%97%E3%83%AC%E3%82%B8%E3%83%87%E3%83%B3%E3%83%86%E3%83%BB%E3%83%A1%E3%83%BC%E3%82%B8%E3%82%B7/R.+Pedro+Pereira+de+Almeida,+11+-+%E3%83%97%E3%83%AC%E3%82%B8%E3%83%87%E3%83%B3%E3%83%86%E3%83%BB%E3%83%A1%E3%83%BC%E3%82%B8%E3%82%B7+Campina+Grande+-+PB,+58417-540/@-7.249428,-35.9091351,18z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0x7ac1dfd93ff626b:0x4c40f9ef5f813126!2m2!1d-35.9080531!2d-7.2494301!1m5!1m1!1s0x7ac1dfd93ff626b:0x4c40f9ef5f813126!2m2!1d-35.9080714!2d-7.2494313"> Mapa </a>
</p>
</p>
	

clinify/app/views/clinify_static_pages/help.html.erb
<%provide(:title, 'Help') %>
<h1> Dicas </h1>
<p>
	Porque fazer Pilates? <a href="http://maisequilibrio.com.br/fitness/pilates-3-1-2-76.html">Veja aqui </a>
</p>
	

clinify/app/views/clinify_static_pages/home.html.erb
<div class="center hero-unit">
	<h1> Bem vindo a Kefisio!</h1>
	<h2> Esta é a homepage da Kefisio. Para acessar sua conta, clique em <%= link_to "Log in" , login_path, class: "btn btn-large btn-primary" %>. </h2>
</div>
	
<%= link_to image_tag("kefisio.png", alt: "Clinify") %>
	

clinify/app/views/clinify_static_pages/login.html.erb
<%provide(:title, 'Login') %>
<h1> Login </h1>
<p>
	Faça seu login
</p>
	

clinify/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" , "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

   <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>

<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Kefisio", '#', id: "logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home",      root_path  %></li>
					<li><%= link_to "Ajuda",     help_path  %></li>
					<li><%= link_to "Sobre nós",    about_path %></li>
					<li><%= link_to "Login",     login_path  %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

	<body>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

clinify/app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userid %><br />
    <%= f.text_field :userid %>
  </div>
  <div class="field">
    <%= f.label :symptoms %><br />
    <%= f.text_field :symptoms %>
  </div>
  <div class="field">
    <%= f.label :exam %><br />
    <%= f.text_field :exam %>
  </div>
  <div class="field">
    <%= f.label :beats %><br />
    <%= f.text_field :beats %>
  </div>
  <div class="field">
    <%= f.label :history %><br />
    <%= f.text_field :history %>
  </div>
  <div class="field">
    <%= f.label :obs %><br />
    <%= f.text_field :obs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

clinify/app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @record %> |
<%= link_to 'Voltar', records_path %>

clinify/app/views/records/index.html.erb
<h1>Listando cadastros</h1>

<table>
  <tr>
    <th>Usuário</th>
    <th>Data de aniversário</th>
    <th>Sintomas</th>
    <th>Exames</th>
    <th>Batimentos</th>
    <th>Histórico pessoal</th>
    <th>Observações</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @records.each do |record| %>
  <tr>
    <td><%= record.userid %></td>
    <td><%= record.birthday %></td>
    <td><%= record.symptoms %></td>
    <td><%= record.exam %></td>
    <td><%= record.beats %></td>
    <td><%= record.history %></td>
    <td><%= record.obs %></td>
    <td><%= link_to 'Mostrar', record %></td>
    <td><%= link_to 'Editar', edit_record_path(record) %></td>
    <td><%= link_to 'Apagar', record, confirm: 'Você tem certeza?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo cadastro', new_record_path %>

clinify/app/views/records/new.html.erb
<h1>Novo cadastro</h1>

<%= render 'form' %>

<%= link_to 'Voltar', records_path %>

clinify/app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Symptoms:</b>
  <%= @record.symptoms %>
</p>

<p>
  <b>Exam:</b>
  <%= @record.exam %>
</p>

<p>
  <b>Beats:</b>
  <%= @record.beats %>
</p>

<p>
  <b>History:</b>
  <%= @record.history %>
</p>

<p>
  <b>Obs:</b>
  <%= @record.obs %>
</p>


<%= link_to 'Editar', edit_record_path(@record) %> |
<%= link_to 'Voltar', records_path %>

clinify/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :senha %><br />
    <%= f.text_field :senha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

clinify/app/views/users/edit.html.erb
<h1>Editar dados</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @user %> |
<%= link_to 'Voltar', users_path %>

clinify/app/views/users/index.html.erb
<h1>Listando pacientes</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Login</th>
    <th>Senha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.login %></td>
    <td><%= user.senha %></td>
    <td><%= link_to 'Mostrar', user %></td>
    <td><%= link_to 'Editar', edit_user_path(user) %></td>
    <td><%= link_to 'Apagar', user, confirm: 'Você tem certeza?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo paciente', new_user_path %>
<%= link_to 'Pesquisar paciente'%>

clinify/app/views/users/new.html.erb
<h1>Novo usuário</h1>

<%= render 'form' %>

<%= link_to 'Voltar', users_path %>

clinify/app/views/users/search.html.erb
<h1>Pesquisar usuário</h1>

<br>

<%= form_tag(searchname_user_path, method: "get") do %>
  <%= label_tag(:q, "Nome do Paciente:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Pesquisar") %>
<% end %>

<br>
<%= link_to 'Voltar', users_path %>

clinify/app/views/users/searchname.html.erb
<h1>Pesquisar usuário</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Login</th>
    <th>Senha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <% if user.name.include? @name %>
    <tr>
    <td><%= user.name %></td>
    <td><%= user.login %></td>
    <td><%= user.senha %></td>
    <td><%= link_to 'Mostrar', user %></td>
    <td><%= link_to 'Editar', edit_user_path(user) %></td>
    <td><%= link_to 'Apagar', user, confirm: 'Você tem certeza?', method: :delete %></td>
    </tr>
  <% end %>
<% end %>
</table>

<%= link_to 'Voltar', users_path %>
<%= link_to 'Pesquisar Novamente', search_user_path %>

clinify/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Login:</b>
  <%= @user.login %>
</p>

<p>
  <b>Senha:</b>
  <%= @user.senha %>
</p>


<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Voltar', users_path %>